
DROP TABLE PRODUTO;
DROP TABLE PACIENTE;
DROP TABLE MEDICO;
DROP TABLE SALA_CIRURGIA;
DROP TABLE ESPECIALIDADE;
DROP TABLE CIRURGIA;
DROP TABLE CIRURGIA_PRODUTO;




CREATE TABLE PRODUTO (
    ID_PRODUTO   INTEGER NOT NULL,
    TP_PRODUTO   VARCHAR2(20) NOT NULL,
    DS_PRODUTO   VARCHAR2(300) NOT NULL,
    QTD_PRODUTO  FLOAT NOT NULL,
    CONSTRAINT PRODUTO_PK PRIMARY KEY ( ID_PRODUTO )
);


CREATE TABLE PACIENTE (
    NUM_REGISTRO  INTEGER NOT NULL,
    CPF           VARCHAR2(14) NOT NULL,
    NOME          VARCHAR2(60) NOT NULL,
    TP_PACIENTE   VARCHAR2(10) NOT NULL,
    TEL_CONTATO   VARCHAR2(12),
    DT_NASC       DATE,
    SEXO          VARCHAR2(9) NOT NULL,
    CONSTRAINT PACIENTE_PK PRIMARY KEY ( NUM_REGISTRO ),
    CONSTRAINT PACIENTE_CPF_UN UNIQUE ( CPF )
);


CREATE TABLE MEDICO (
    NR_REG_MEDICO  INTEGER NOT NULL,
    NOME           VARCHAR2(60) NOT NULL,
    TELEFONE       VARCHAR2(12) NOT NULL,
    CONSTRAINT MEDICO_PK PRIMARY KEY ( NR_REG_MEDICO )
);


CREATE TABLE SALA_CIRURGIA (NR_SALA INTEGER PRIMARY KEY ) ; 


CREATE TABLE ESPECIALIDADE (
    ID_ESPECIALIDADE       INTEGER NOT NULL,
    DS_ESPECIALIDADE       VARCHAR2(40) NOT NULL,
    MEDICO_NR_REG_MEDICO   INTEGER NOT NULL,
    SALA_CIRURGIA_NR_SALA  INTEGER NOT NULL,
    CONSTRAINT ESPECIALIDADE_MEDICO_FK FOREIGN KEY ( MEDICO_NR_REG_MEDICO )
        REFERENCES MEDICO ( NR_REG_MEDICO ),
    CONSTRAINT ESPECIALIDADE_SALA_CIRURGIA_FK FOREIGN KEY ( SALA_CIRURGIA_NR_SALA )
        REFERENCES SALA_CIRURGIA ( NR_SALA )
) ;


CREATE TABLE CIRURGIA (
    ID_CIRURGIA            INTEGER NOT NULL,
    TP_CIRURGIA            VARCHAR2(10) NOT NULL,
    DS_CIRURGIA            VARCHAR2(2000) NOT NULL,
    DATA_CIRURGIA          DATE NOT NULL,
    HORA_CIRURGIA          TIMESTAMP NOT NULL,
    ESTADO_CIRURGIA        VARCHAR2(20) NOT NULL,
    MEDICO_NR_REG_MEDICO   INTEGER NOT NULL,
    SALA_CIRURGIA_NR_SALA  INTEGER NOT NULL,
    PACIENTE_NUM_REGISTRO  INTEGER NOT NULL,
    CONSTRAINT CIRURGIA_PK PRIMARY KEY ( ID_CIRURGIA ),
    CONSTRAINT CIRURGIA_MEDICO_FK FOREIGN KEY ( MEDICO_NR_REG_MEDICO )
        REFERENCES MEDICO ( NR_REG_MEDICO ),
    CONSTRAINT CIRURGIA_PACIENTE_FK FOREIGN KEY ( PACIENTE_NUM_REGISTRO )
        REFERENCES PACIENTE ( NUM_REGISTRO ),
    CONSTRAINT CIRURGIA_SALA_CIRURGIA_FK FOREIGN KEY ( SALA_CIRURGIA_NR_SALA )
        REFERENCES SALA_CIRURGIA ( NR_SALA )
);


CREATE TABLE CIRURGIA_PRODUTO (
    DATA_CONSUMO          DATE NOT NULL,
    HORA_CONSUMO          TIMESTAMP NOT NULL,
    QTD_CONSUMIDA         FLOAT NOT NULL,
    PRODUTO_ID_PRODUTO    INTEGER NOT NULL,
    CIRURGIA_ID_CIRURGIA  INTEGER NOT NULL,
    CONSTRAINT CIRURGIA_PRODUTO_CIRURGIA_FK FOREIGN KEY ( CIRURGIA_ID_CIRURGIA )
        REFERENCES CIRURGIA ( ID_CIRURGIA ),
    CONSTRAINT CIRURGIA_PRODUTO_PRODUTO_FK FOREIGN KEY ( PRODUTO_ID_PRODUTO )
        REFERENCES PRODUTO ( ID_PRODUTO )
);

